# 빌드 스테이지
FROM node:20-alpine as build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY ./ ./
RUN yarn build

# 실행 스테이지
FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/build ./build
RUN yarn global add serve
CMD ["serve", "-s", "build"]
