# 빌드 스테이지
FROM node:20-alpine as build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY ./ ./
RUN yarn build

# 실행 스테이지
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
